//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachGDHTCuThe
    {
        public int Id { get; set; }
        public int DeCuongChiTiet_Id { get; set; }
        public string Buoi { get; set; }
        public Nullable<int> SoTietLenLop { get; set; }
        public string NoiDungBaiHoc { get; set; }
        public string HoatDongDayVaHoc { get; set; }
        public string TaiLieuCanDoc { get; set; }
    
        public virtual DeCuongChiTiet DeCuongChiTiet { get; set; }
    }
}
