//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuanDauRaMonHoc> ChuanDauRaMonHocs { get; set; }
        public virtual DbSet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos { get; set; }
        public virtual DbSet<DeCuongChiTiet> DeCuongChiTiets { get; set; }
        public virtual DbSet<GVGD> GVGDs { get; set; }
        public virtual DbSet<KeHoachGDHTCuThe> KeHoachGDHTCuThes { get; set; }
        public virtual DbSet<KeHoanKiemTra> KeHoanKiemTras { get; set; }
        public virtual DbSet<MaTran_CDRMH_CDRCTDT> MaTran_CDRMH_CDRCTDT { get; set; }
        public virtual DbSet<MaTran_ChuanDauRaMH_HDGDPPDG> MaTran_ChuanDauRaMH_HDGDPPDG { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<MonTienQuyet> MonTienQuyets { get; set; }
        public virtual DbSet<MucTieuDaoTao> MucTieuDaoTaos { get; set; }
        public virtual DbSet<MucTieuMonHoc> MucTieuMonHocs { get; set; }
        public virtual DbSet<PhanQuyenTaiKhoan> PhanQuyenTaiKhoans { get; set; }
        public virtual DbSet<PPDanhGiaKQHT> PPDanhGiaKQHTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TaiLieuMonHoc> TaiLieuMonHocs { get; set; }
        public virtual DbSet<ThongTinChung_CTDT> ThongTinChung_CTDT { get; set; }
    
        public virtual int Admin_createCTDT_Thinh(string tenCTDT, Nullable<int> nguoiPhuTrachID, Nullable<int> copyTuCTDT)
        {
            var tenCTDTParameter = tenCTDT != null ?
                new ObjectParameter("TenCTDT", tenCTDT) :
                new ObjectParameter("TenCTDT", typeof(string));
    
            var nguoiPhuTrachIDParameter = nguoiPhuTrachID.HasValue ?
                new ObjectParameter("NguoiPhuTrachID", nguoiPhuTrachID) :
                new ObjectParameter("NguoiPhuTrachID", typeof(int));
    
            var copyTuCTDTParameter = copyTuCTDT.HasValue ?
                new ObjectParameter("CopyTuCTDT", copyTuCTDT) :
                new ObjectParameter("CopyTuCTDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Admin_createCTDT_Thinh", tenCTDTParameter, nguoiPhuTrachIDParameter, copyTuCTDTParameter);
        }
    
        public virtual int Admin_createThongTinChungCTDT_Thinh(string tenCTDT)
        {
            var tenCTDTParameter = tenCTDT != null ?
                new ObjectParameter("TenCTDT", tenCTDT) :
                new ObjectParameter("TenCTDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Admin_createThongTinChungCTDT_Thinh", tenCTDTParameter);
        }
    
        public virtual ObjectResult<Admin_CTDTSearch_Result> Admin_CTDTSearch(string tEXTSEARCH)
        {
            var tEXTSEARCHParameter = tEXTSEARCH != null ?
                new ObjectParameter("TEXTSEARCH", tEXTSEARCH) :
                new ObjectParameter("TEXTSEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_CTDTSearch_Result>("Admin_CTDTSearch", tEXTSEARCHParameter);
        }
    
        public virtual ObjectResult<Admin_CTDTSelectAll_Result> Admin_CTDTSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_CTDTSelectAll_Result>("Admin_CTDTSelectAll");
        }
    
        public virtual int Admin_updateCTDT_Thinh(Nullable<int> id, string tenCTDT, Nullable<int> nguoiPhuTrachID, Nullable<int> copyTuCTDT)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenCTDTParameter = tenCTDT != null ?
                new ObjectParameter("TenCTDT", tenCTDT) :
                new ObjectParameter("TenCTDT", typeof(string));
    
            var nguoiPhuTrachIDParameter = nguoiPhuTrachID.HasValue ?
                new ObjectParameter("NguoiPhuTrachID", nguoiPhuTrachID) :
                new ObjectParameter("NguoiPhuTrachID", typeof(int));
    
            var copyTuCTDTParameter = copyTuCTDT.HasValue ?
                new ObjectParameter("CopyTuCTDT", copyTuCTDT) :
                new ObjectParameter("CopyTuCTDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Admin_updateCTDT_Thinh", idParameter, tenCTDTParameter, nguoiPhuTrachIDParameter, copyTuCTDTParameter);
        }
    
        public virtual int Authorize_Create_Sang(Nullable<int> tK_Id, string chucVu)
        {
            var tK_IdParameter = tK_Id.HasValue ?
                new ObjectParameter("TK_Id", tK_Id) :
                new ObjectParameter("TK_Id", typeof(int));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Authorize_Create_Sang", tK_IdParameter, chucVuParameter);
        }
    
        public virtual ObjectResult<Authorize_Search_Sang_Result> Authorize_Search_Sang(string tEXTSEARCH)
        {
            var tEXTSEARCHParameter = tEXTSEARCH != null ?
                new ObjectParameter("TEXTSEARCH", tEXTSEARCH) :
                new ObjectParameter("TEXTSEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Authorize_Search_Sang_Result>("Authorize_Search_Sang", tEXTSEARCHParameter);
        }
    
        public virtual ObjectResult<Authorize_Select_Sang_Result> Authorize_Select_Sang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Authorize_Select_Sang_Result>("Authorize_Select_Sang");
        }
    
        public virtual int Authorize_Update_Sang(Nullable<int> tK_Id, string chucVu)
        {
            var tK_IdParameter = tK_Id.HasValue ?
                new ObjectParameter("TK_Id", tK_Id) :
                new ObjectParameter("TK_Id", typeof(int));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Authorize_Update_Sang", tK_IdParameter, chucVuParameter);
        }
    
        public virtual int Course_Update_Sang(Nullable<int> id, string tenDCCT, string tenTiengAnh, string nDVT, string maHP)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tenDCCTParameter = tenDCCT != null ?
                new ObjectParameter("TenDCCT", tenDCCT) :
                new ObjectParameter("TenDCCT", typeof(string));
    
            var tenTiengAnhParameter = tenTiengAnh != null ?
                new ObjectParameter("TenTiengAnh", tenTiengAnh) :
                new ObjectParameter("TenTiengAnh", typeof(string));
    
            var nDVTParameter = nDVT != null ?
                new ObjectParameter("NDVT", nDVT) :
                new ObjectParameter("NDVT", typeof(string));
    
            var maHPParameter = maHP != null ?
                new ObjectParameter("MaHP", maHP) :
                new ObjectParameter("MaHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Course_Update_Sang", idParameter, tenDCCTParameter, tenTiengAnhParameter, nDVTParameter, maHPParameter);
        }
    
        public virtual ObjectResult<CTDT_Select_Sang_Result> CTDT_Select_Sang(Nullable<int> accID)
        {
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDT_Select_Sang_Result>("CTDT_Select_Sang", accIDParameter);
        }
    
        public virtual ObjectResult<CTDT_SelectFinishFalse_Sang_Result> CTDT_SelectFinishFalse_Sang(Nullable<int> accID)
        {
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDT_SelectFinishFalse_Sang_Result>("CTDT_SelectFinishFalse_Sang", accIDParameter);
        }
    
        public virtual ObjectResult<CTDT_SelectFinishTrue_Sang_Result> CTDT_SelectFinishTrue_Sang(Nullable<int> accID)
        {
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDT_SelectFinishTrue_Sang_Result>("CTDT_SelectFinishTrue_Sang", accIDParameter);
        }
    
        public virtual ObjectResult<CTDT_SelectForGV_Sang_Result> CTDT_SelectForGV_Sang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDT_SelectForGV_Sang_Result>("CTDT_SelectForGV_Sang");
        }
    
        public virtual ObjectResult<DCCT_Select_Sang_Result> DCCT_Select_Sang(Nullable<int> accID)
        {
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DCCT_Select_Sang_Result>("DCCT_Select_Sang", accIDParameter);
        }
    
        public virtual ObjectResult<DCCT_SelectFinishFalse_Sang_Result> DCCT_SelectFinishFalse_Sang(Nullable<int> accID)
        {
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DCCT_SelectFinishFalse_Sang_Result>("DCCT_SelectFinishFalse_Sang", accIDParameter);
        }
    
        public virtual ObjectResult<DCCT_SelectFinishTrue_Sang_Result> DCCT_SelectFinishTrue_Sang(Nullable<int> accID)
        {
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DCCT_SelectFinishTrue_Sang_Result>("DCCT_SelectFinishTrue_Sang", accIDParameter);
        }
    
        public virtual ObjectResult<DCCT_SelectForGV_Sang_Result> DCCT_SelectForGV_Sang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DCCT_SelectForGV_Sang_Result>("DCCT_SelectForGV_Sang");
        }
    
        public virtual int DetailedSyllabus_CreateDetailedSyllabus_MaTran2CDR_Sang(Nullable<int> dCCT_Id, Nullable<int> cDRMH_Id, Nullable<int> cDRCTDT_Id, Nullable<bool> mapping)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var cDRMH_IdParameter = cDRMH_Id.HasValue ?
                new ObjectParameter("CDRMH_Id", cDRMH_Id) :
                new ObjectParameter("CDRMH_Id", typeof(int));
    
            var cDRCTDT_IdParameter = cDRCTDT_Id.HasValue ?
                new ObjectParameter("CDRCTDT_Id", cDRCTDT_Id) :
                new ObjectParameter("CDRCTDT_Id", typeof(int));
    
            var mappingParameter = mapping.HasValue ?
                new ObjectParameter("Mapping", mapping) :
                new ObjectParameter("Mapping", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_CreateDetailedSyllabus_MaTran2CDR_Sang", dCCT_IdParameter, cDRMH_IdParameter, cDRCTDT_IdParameter, mappingParameter);
        }
    
        public virtual int DetailedSyllabus_CreateDetailedSyllabus_MaTranCDRHDDG_Sang(Nullable<int> cDRMH_Id, string loai, string noiDung)
        {
            var cDRMH_IdParameter = cDRMH_Id.HasValue ?
                new ObjectParameter("CDRMH_Id", cDRMH_Id) :
                new ObjectParameter("CDRMH_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_CreateDetailedSyllabus_MaTranCDRHDDG_Sang", cDRMH_IdParameter, loaiParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_CreateGVGD_Sang(Nullable<int> dCCT_Id, string dChi, string dthoai, string email, string troG, string tenGV)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var dChiParameter = dChi != null ?
                new ObjectParameter("DChi", dChi) :
                new ObjectParameter("DChi", typeof(string));
    
            var dthoaiParameter = dthoai != null ?
                new ObjectParameter("Dthoai", dthoai) :
                new ObjectParameter("Dthoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var troGParameter = troG != null ?
                new ObjectParameter("TroG", troG) :
                new ObjectParameter("TroG", typeof(string));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_CreateGVGD_Sang", dCCT_IdParameter, dChiParameter, dthoaiParameter, emailParameter, troGParameter, tenGVParameter);
        }
    
        public virtual int DetailedSyllabus_CreateKHKT(Nullable<int> dcctid, string hinhthuc, string noidung, string thoidiem, string congcukt)
        {
            var dcctidParameter = dcctid.HasValue ?
                new ObjectParameter("dcctid", dcctid) :
                new ObjectParameter("dcctid", typeof(int));
    
            var hinhthucParameter = hinhthuc != null ?
                new ObjectParameter("hinhthuc", hinhthuc) :
                new ObjectParameter("hinhthuc", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var thoidiemParameter = thoidiem != null ?
                new ObjectParameter("thoidiem", thoidiem) :
                new ObjectParameter("thoidiem", typeof(string));
    
            var congcuktParameter = congcukt != null ?
                new ObjectParameter("congcukt", congcukt) :
                new ObjectParameter("congcukt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_CreateKHKT", dcctidParameter, hinhthucParameter, noidungParameter, thoidiemParameter, congcuktParameter);
        }
    
        public virtual int DetailedSyllabus_CreateMTMH_Sang(Nullable<int> dCCT_Id, string loai, string noiDung, Nullable<double> stt)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sttParameter = stt.HasValue ?
                new ObjectParameter("Stt", stt) :
                new ObjectParameter("Stt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_CreateMTMH_Sang", dCCT_IdParameter, loaiParameter, noiDungParameter, sttParameter);
        }
    
        public virtual int DetailedSyllabus_CreatePPDGKQHT(Nullable<int> dcctid, string loainoidung, string solandanhgia, Nullable<int> trongso, string hinhthucdanhgia)
        {
            var dcctidParameter = dcctid.HasValue ?
                new ObjectParameter("dcctid", dcctid) :
                new ObjectParameter("dcctid", typeof(int));
    
            var loainoidungParameter = loainoidung != null ?
                new ObjectParameter("loainoidung", loainoidung) :
                new ObjectParameter("loainoidung", typeof(string));
    
            var solandanhgiaParameter = solandanhgia != null ?
                new ObjectParameter("solandanhgia", solandanhgia) :
                new ObjectParameter("solandanhgia", typeof(string));
    
            var trongsoParameter = trongso.HasValue ?
                new ObjectParameter("trongso", trongso) :
                new ObjectParameter("trongso", typeof(int));
    
            var hinhthucdanhgiaParameter = hinhthucdanhgia != null ?
                new ObjectParameter("hinhthucdanhgia", hinhthucdanhgia) :
                new ObjectParameter("hinhthucdanhgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_CreatePPDGKQHT", dcctidParameter, loainoidungParameter, solandanhgiaParameter, trongsoParameter, hinhthucdanhgiaParameter);
        }
    
        public virtual int DetailedSyllabus_Delete_MT_CDRMH_HDGDPPGD(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_Delete_MT_CDRMH_HDGDPPGD", idParameter);
        }
    
        public virtual int DetailedSyllabus_deleteDetailedSyllabus_ChuanDauRaMonHoc_Sang(Nullable<int> deCuongChiTiet_Id, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_deleteDetailedSyllabus_ChuanDauRaMonHoc_Sang", deCuongChiTiet_IdParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_DeleteDetailedSyllabus_MaTran2CDR_Sang(Nullable<int> dCCT_Id, Nullable<int> cDRMH_Id)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var cDRMH_IdParameter = cDRMH_Id.HasValue ?
                new ObjectParameter("CDRMH_Id", cDRMH_Id) :
                new ObjectParameter("CDRMH_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_DeleteDetailedSyllabus_MaTran2CDR_Sang", dCCT_IdParameter, cDRMH_IdParameter);
        }
    
        public virtual int DetailedSyllabus_DeleteDetailedSyllabus_MaTranCDRvsHDGD_Sang(Nullable<int> cDRMH_Id)
        {
            var cDRMH_IdParameter = cDRMH_Id.HasValue ?
                new ObjectParameter("CDRMH_Id", cDRMH_Id) :
                new ObjectParameter("CDRMH_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_DeleteDetailedSyllabus_MaTranCDRvsHDGD_Sang", cDRMH_IdParameter);
        }
    
        public virtual int DetailedSyllabus_DeleteKHKT(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_DeleteKHKT", idParameter);
        }
    
        public virtual int DetailedSyllabus_DeleteMaTranCDRHD_Sang(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_DeleteMaTranCDRHD_Sang", iDParameter);
        }
    
        public virtual int DetailedSyllabus_DeleteMTMH_Sang(Nullable<int> deCuongChiTiet_Id, string loai, string noiDung, Nullable<double> sTT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_DeleteMTMH_Sang", deCuongChiTiet_IdParameter, loaiParameter, noiDungParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_DeletePPDGKQHT(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_DeletePPDGKQHT", idParameter);
        }
    
        public virtual int DetailedSyllabus_deleteTaiLieu_Sang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_deleteTaiLieu_Sang", idParameter);
        }
    
        public virtual int DetailedSyllabus_HoanThanh_Sang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_HoanThanh_Sang", idParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Sang(Nullable<int> deCuongChiTiet_Id, Nullable<int> sTT, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Sang", deCuongChiTiet_IdParameter, sTTParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Thinh(Nullable<int> deCuongChiTiet_Id, Nullable<int> sTT, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_ChuanDauRaMonHoc_Thinh", deCuongChiTiet_IdParameter, sTTParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateDetailedSyllabus_HPHT_Sang(Nullable<int> id, Nullable<int> mH_ID, Nullable<int> mTQ_ID, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var mH_IDParameter = mH_ID.HasValue ?
                new ObjectParameter("MH_ID", mH_ID) :
                new ObjectParameter("MH_ID", typeof(int));
    
            var mTQ_IDParameter = mTQ_ID.HasValue ?
                new ObjectParameter("MTQ_ID", mTQ_ID) :
                new ObjectParameter("MTQ_ID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateDetailedSyllabus_HPHT_Sang", idParameter, mH_IDParameter, mTQ_IDParameter, statusParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_KeHoanKiemTra_Thinh(Nullable<int> deCuongChiTiet_Id, string hinhThuc, string noiDung, string thoiDiem, string congCuKT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var hinhThucParameter = hinhThuc != null ?
                new ObjectParameter("HinhThuc", hinhThuc) :
                new ObjectParameter("HinhThuc", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var thoiDiemParameter = thoiDiem != null ?
                new ObjectParameter("ThoiDiem", thoiDiem) :
                new ObjectParameter("ThoiDiem", typeof(string));
    
            var congCuKTParameter = congCuKT != null ?
                new ObjectParameter("CongCuKT", congCuKT) :
                new ObjectParameter("CongCuKT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_KeHoanKiemTra_Thinh", deCuongChiTiet_IdParameter, hinhThucParameter, noiDungParameter, thoiDiemParameter, congCuKTParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MaTran_CDRMH_CDRCTDT_Thinh(Nullable<int> chuanDauRaMonHoc_Id, Nullable<int> mucTieuDaoTao_Id, Nullable<bool> status)
        {
            var chuanDauRaMonHoc_IdParameter = chuanDauRaMonHoc_Id.HasValue ?
                new ObjectParameter("ChuanDauRaMonHoc_Id", chuanDauRaMonHoc_Id) :
                new ObjectParameter("ChuanDauRaMonHoc_Id", typeof(int));
    
            var mucTieuDaoTao_IdParameter = mucTieuDaoTao_Id.HasValue ?
                new ObjectParameter("MucTieuDaoTao_Id", mucTieuDaoTao_Id) :
                new ObjectParameter("MucTieuDaoTao_Id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MaTran_CDRMH_CDRCTDT_Thinh", chuanDauRaMonHoc_IdParameter, mucTieuDaoTao_IdParameter, statusParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh(Nullable<int> chuanDauRaMonHoc_Id, string phuongPhapDanhGia, string hoatDongDanhGia, Nullable<int> sTT)
        {
            var chuanDauRaMonHoc_IdParameter = chuanDauRaMonHoc_Id.HasValue ?
                new ObjectParameter("ChuanDauRaMonHoc_Id", chuanDauRaMonHoc_Id) :
                new ObjectParameter("ChuanDauRaMonHoc_Id", typeof(int));
    
            var phuongPhapDanhGiaParameter = phuongPhapDanhGia != null ?
                new ObjectParameter("PhuongPhapDanhGia", phuongPhapDanhGia) :
                new ObjectParameter("PhuongPhapDanhGia", typeof(string));
    
            var hoatDongDanhGiaParameter = hoatDongDanhGia != null ?
                new ObjectParameter("HoatDongDanhGia", hoatDongDanhGia) :
                new ObjectParameter("HoatDongDanhGia", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh", chuanDauRaMonHoc_IdParameter, phuongPhapDanhGiaParameter, hoatDongDanhGiaParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateDetailedSyllabus_MaTran2CDR_Sang(Nullable<int> dCCT_Id, Nullable<int> cDRMH_Id, Nullable<int> cDRCTDT_Id, Nullable<bool> mapping)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var cDRMH_IdParameter = cDRMH_Id.HasValue ?
                new ObjectParameter("CDRMH_Id", cDRMH_Id) :
                new ObjectParameter("CDRMH_Id", typeof(int));
    
            var cDRCTDT_IdParameter = cDRCTDT_Id.HasValue ?
                new ObjectParameter("CDRCTDT_Id", cDRCTDT_Id) :
                new ObjectParameter("CDRCTDT_Id", typeof(int));
    
            var mappingParameter = mapping.HasValue ?
                new ObjectParameter("Mapping", mapping) :
                new ObjectParameter("Mapping", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateDetailedSyllabus_MaTran2CDR_Sang", dCCT_IdParameter, cDRMH_IdParameter, cDRCTDT_IdParameter, mappingParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_MucTieuMonHoc_Thinh(Nullable<int> deCuongChiTiet_Id, string loai, string noiDung, Nullable<int> sTT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_MucTieuMonHoc_Thinh", deCuongChiTiet_IdParameter, loaiParameter, noiDungParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_PPDanhGia_Thinh(Nullable<int> deCuongChiTiet_Id, string loaiNoiDung, string soLanDanhGia, string trongSo, string hinhThucDanhGia)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiNoiDungParameter = loaiNoiDung != null ?
                new ObjectParameter("LoaiNoiDung", loaiNoiDung) :
                new ObjectParameter("LoaiNoiDung", typeof(string));
    
            var soLanDanhGiaParameter = soLanDanhGia != null ?
                new ObjectParameter("SoLanDanhGia", soLanDanhGia) :
                new ObjectParameter("SoLanDanhGia", typeof(string));
    
            var trongSoParameter = trongSo != null ?
                new ObjectParameter("TrongSo", trongSo) :
                new ObjectParameter("TrongSo", typeof(string));
    
            var hinhThucDanhGiaParameter = hinhThucDanhGia != null ?
                new ObjectParameter("HinhThucDanhGia", hinhThucDanhGia) :
                new ObjectParameter("HinhThucDanhGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_PPDanhGia_Thinh", deCuongChiTiet_IdParameter, loaiNoiDungParameter, soLanDanhGiaParameter, trongSoParameter, hinhThucDanhGiaParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateDetailedSyllabus_Sang(Nullable<int> id, string tenDCCT, string tenTiengAnh, string trinhDo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tenDCCTParameter = tenDCCT != null ?
                new ObjectParameter("TenDCCT", tenDCCT) :
                new ObjectParameter("TenDCCT", typeof(string));
    
            var tenTiengAnhParameter = tenTiengAnh != null ?
                new ObjectParameter("TenTiengAnh", tenTiengAnh) :
                new ObjectParameter("TenTiengAnh", typeof(string));
    
            var trinhDoParameter = trinhDo != null ?
                new ObjectParameter("TrinhDo", trinhDo) :
                new ObjectParameter("TrinhDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateDetailedSyllabus_Sang", idParameter, tenDCCTParameter, tenTiengAnhParameter, trinhDoParameter);
        }
    
        public virtual int DetailedSyllabus_updateDetailedSyllabus_TaiLieuMonHoc_Thinh(Nullable<int> deCuongChiTiet_Id, string loai, string noiDung, Nullable<double> sTT)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateDetailedSyllabus_TaiLieuMonHoc_Thinh", deCuongChiTiet_IdParameter, loaiParameter, noiDungParameter, sTTParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateGVGD_Sang(Nullable<int> dCCT_Id, string dChi, string dthoai, string email, string troG, string tenGV)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var dChiParameter = dChi != null ?
                new ObjectParameter("DChi", dChi) :
                new ObjectParameter("DChi", typeof(string));
    
            var dthoaiParameter = dthoai != null ?
                new ObjectParameter("Dthoai", dthoai) :
                new ObjectParameter("Dthoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var troGParameter = troG != null ?
                new ObjectParameter("TroG", troG) :
                new ObjectParameter("TroG", typeof(string));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateGVGD_Sang", dCCT_IdParameter, dChiParameter, dthoaiParameter, emailParameter, troGParameter, tenGVParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateKHKT(Nullable<int> id, Nullable<int> dcctid, string hinhthuc, string noidung, string thoidiem, string congcukt)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dcctidParameter = dcctid.HasValue ?
                new ObjectParameter("dcctid", dcctid) :
                new ObjectParameter("dcctid", typeof(int));
    
            var hinhthucParameter = hinhthuc != null ?
                new ObjectParameter("hinhthuc", hinhthuc) :
                new ObjectParameter("hinhthuc", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var thoidiemParameter = thoidiem != null ?
                new ObjectParameter("thoidiem", thoidiem) :
                new ObjectParameter("thoidiem", typeof(string));
    
            var congcuktParameter = congcukt != null ?
                new ObjectParameter("congcukt", congcukt) :
                new ObjectParameter("congcukt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateKHKT", idParameter, dcctidParameter, hinhthucParameter, noidungParameter, thoidiemParameter, congcuktParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateMaTranCDRHD_Sang(Nullable<int> iD, string noiDung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateMaTranCDRHD_Sang", iDParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateMTMH_Sang(Nullable<int> dCCT_Id, string loai, string noiDung, Nullable<double> stt)
        {
            var dCCT_IdParameter = dCCT_Id.HasValue ?
                new ObjectParameter("DCCT_Id", dCCT_Id) :
                new ObjectParameter("DCCT_Id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var sttParameter = stt.HasValue ?
                new ObjectParameter("Stt", stt) :
                new ObjectParameter("Stt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateMTMH_Sang", dCCT_IdParameter, loaiParameter, noiDungParameter, sttParameter);
        }
    
        public virtual int DetailedSyllabus_UpdatePPDGKQHT(Nullable<int> id, Nullable<int> dcctid, string loainoidung, string solandanhgia, Nullable<int> trongso, string hinhthucdanhgia)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dcctidParameter = dcctid.HasValue ?
                new ObjectParameter("dcctid", dcctid) :
                new ObjectParameter("dcctid", typeof(int));
    
            var loainoidungParameter = loainoidung != null ?
                new ObjectParameter("loainoidung", loainoidung) :
                new ObjectParameter("loainoidung", typeof(string));
    
            var solandanhgiaParameter = solandanhgia != null ?
                new ObjectParameter("solandanhgia", solandanhgia) :
                new ObjectParameter("solandanhgia", typeof(string));
    
            var trongsoParameter = trongso.HasValue ?
                new ObjectParameter("trongso", trongso) :
                new ObjectParameter("trongso", typeof(int));
    
            var hinhthucdanhgiaParameter = hinhthucdanhgia != null ?
                new ObjectParameter("hinhthucdanhgia", hinhthucdanhgia) :
                new ObjectParameter("hinhthucdanhgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdatePPDGKQHT", idParameter, dcctidParameter, loainoidungParameter, solandanhgiaParameter, trongsoParameter, hinhthucdanhgiaParameter);
        }
    
        public virtual int DetailedSyllabus_updateSTTDetailedSyllabus_ChuanDauRaMonHoc_Sang(Nullable<int> deCuongChiTiet_Id, Nullable<int> sTT, string noiDung)
        {
            var deCuongChiTiet_IdParameter = deCuongChiTiet_Id.HasValue ?
                new ObjectParameter("DeCuongChiTiet_Id", deCuongChiTiet_Id) :
                new ObjectParameter("DeCuongChiTiet_Id", typeof(int));
    
            var sTTParameter = sTT.HasValue ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_updateSTTDetailedSyllabus_ChuanDauRaMonHoc_Sang", deCuongChiTiet_IdParameter, sTTParameter, noiDungParameter);
        }
    
        public virtual int DetailedSyllabus_UpdateTaiLieu_Sang(Nullable<int> id, string noiDung)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DetailedSyllabus_UpdateTaiLieu_Sang", idParameter, noiDungParameter);
        }
    
        public virtual ObjectResult<Load_DCCT_Thinh_Result> Load_DCCT_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_DCCT_Thinh_Result>("Load_DCCT_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_KeHoachKiemTra_Thinh_Result> Load_KeHoachKiemTra_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_KeHoachKiemTra_Thinh_Result>("Load_KeHoachKiemTra_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_KetHoachGiangDay_MonHoc_Thinh_Result> Load_KetHoachGiangDay_MonHoc_Thinh(Nullable<int> id, Nullable<int> hocKi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hocKiParameter = hocKi.HasValue ?
                new ObjectParameter("HocKi", hocKi) :
                new ObjectParameter("HocKi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_KetHoachGiangDay_MonHoc_Thinh_Result>("Load_KetHoachGiangDay_MonHoc_Thinh", idParameter, hocKiParameter);
        }
    
        public virtual ObjectResult<string> Load_LoaiTaiLieu_Thinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Load_LoaiTaiLieu_Thinh");
        }
    
        public virtual int Load_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Load_MaTran_ChuanDauRaMH_HDGDPPDG_Thinh", idParameter);
        }
    
        public virtual ObjectResult<string> Load_MonHocTienQuyet_Thinh(Nullable<int> id, string hk)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hkParameter = hk != null ?
                new ObjectParameter("hk", hk) :
                new ObjectParameter("hk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Load_MonHocTienQuyet_Thinh", idParameter, hkParameter);
        }
    
        public virtual ObjectResult<Load_MucTieu_MonHoc_Thinh_Result> Load_MucTieu_MonHoc_Thinh(Nullable<int> id, Nullable<int> hocKi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hocKiParameter = hocKi.HasValue ?
                new ObjectParameter("HocKi", hocKi) :
                new ObjectParameter("HocKi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_MucTieu_MonHoc_Thinh_Result>("Load_MucTieu_MonHoc_Thinh", idParameter, hocKiParameter);
        }
    
        public virtual ObjectResult<Load_MucTieuMonHoc_Thinh_Result> Load_MucTieuMonHoc_Thinh(Nullable<int> id, string loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_MucTieuMonHoc_Thinh_Result>("Load_MucTieuMonHoc_Thinh", idParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Load_NoiDungChuongTrinh_MonHoc_Thinh_Result> Load_NoiDungChuongTrinh_MonHoc_Thinh(Nullable<int> id, string loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_NoiDungChuongTrinh_MonHoc_Thinh_Result>("Load_NoiDungChuongTrinh_MonHoc_Thinh", idParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Load_NoiDungVanTat_MonHoc_Thinh_Result> Load_NoiDungVanTat_MonHoc_Thinh(Nullable<int> id, Nullable<int> hocKi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hocKiParameter = hocKi.HasValue ?
                new ObjectParameter("HocKi", hocKi) :
                new ObjectParameter("HocKi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_NoiDungVanTat_MonHoc_Thinh_Result>("Load_NoiDungVanTat_MonHoc_Thinh", idParameter, hocKiParameter);
        }
    
        public virtual ObjectResult<Load_PPDanhGia_Thinh_Result> Load_PPDanhGia_Thinh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_PPDanhGia_Thinh_Result>("Load_PPDanhGia_Thinh", idParameter);
        }
    
        public virtual ObjectResult<Load_TaiLieu_MonHoc_Thinh_Result> Load_TaiLieu_MonHoc_Thinh(Nullable<int> id, string loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_TaiLieu_MonHoc_Thinh_Result>("Load_TaiLieu_MonHoc_Thinh", idParameter, loaiParameter);
        }
    
        public virtual ObjectResult<string> Load_TienQuyet_MonHoc_Thinh(Nullable<int> id, string hk)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var hkParameter = hk != null ?
                new ObjectParameter("hk", hk) :
                new ObjectParameter("hk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Load_TienQuyet_MonHoc_Thinh", idParameter, hkParameter);
        }
    
        public virtual ObjectResult<LoadChuanDauRaCTDTTheoMonHoc_Result> LoadChuanDauRaCTDTTheoMonHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoadChuanDauRaCTDTTheoMonHoc_Result>("LoadChuanDauRaCTDTTheoMonHoc");
        }
    
        public virtual ObjectResult<MonTienQuyet_Select_Sang_Result> MonTienQuyet_Select_Sang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonTienQuyet_Select_Sang_Result>("MonTienQuyet_Select_Sang", idParameter);
        }
    
        public virtual ObjectResult<Search_CTDT_Sang_Result> Search_CTDT_Sang(string tEXTSEARCH, Nullable<int> accID)
        {
            var tEXTSEARCHParameter = tEXTSEARCH != null ?
                new ObjectParameter("TEXTSEARCH", tEXTSEARCH) :
                new ObjectParameter("TEXTSEARCH", typeof(string));
    
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_CTDT_Sang_Result>("Search_CTDT_Sang", tEXTSEARCHParameter, accIDParameter);
        }
    
        public virtual ObjectResult<Search_DCCT_Sang_Result> Search_DCCT_Sang(string tEXTSEARCH, Nullable<int> accID)
        {
            var tEXTSEARCHParameter = tEXTSEARCH != null ?
                new ObjectParameter("TEXTSEARCH", tEXTSEARCH) :
                new ObjectParameter("TEXTSEARCH", typeof(string));
    
            var accIDParameter = accID.HasValue ?
                new ObjectParameter("accID", accID) :
                new ObjectParameter("accID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_DCCT_Sang_Result>("Search_DCCT_Sang", tEXTSEARCHParameter, accIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_MONHOC_DELETE(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MONHOC_DELETE", idParameter);
        }
    
        public virtual ObjectResult<SP_MONHOC_VIEW_Result> SP_MONHOC_VIEW(Nullable<int> ctdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MONHOC_VIEW_Result>("SP_MONHOC_VIEW", ctdtParameter);
        }
    
        public virtual int SP_MONTIENQUYET_DEL(Nullable<int> idmonhoc)
        {
            var idmonhocParameter = idmonhoc.HasValue ?
                new ObjectParameter("idmonhoc", idmonhoc) :
                new ObjectParameter("idmonhoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MONTIENQUYET_DEL", idmonhocParameter);
        }
    
        public virtual ObjectResult<SP_MONTIENQUYET_GET_Result> SP_MONTIENQUYET_GET(Nullable<int> ctdt, Nullable<int> hk, Nullable<int> id)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            var hkParameter = hk.HasValue ?
                new ObjectParameter("hk", hk) :
                new ObjectParameter("hk", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MONTIENQUYET_GET_Result>("SP_MONTIENQUYET_GET", ctdtParameter, hkParameter, idParameter);
        }
    
        public virtual ObjectResult<SP_MONTIENQUYET_GETTRUE_Result> SP_MONTIENQUYET_GETTRUE(Nullable<int> ctdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MONTIENQUYET_GETTRUE_Result>("SP_MONTIENQUYET_GETTRUE", ctdtParameter);
        }
    
        public virtual int SP_MUCTIEUDAOTAO_DEL(Nullable<int> ctdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MUCTIEUDAOTAO_DEL", ctdtParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<SP_TAIKHOAN_SEARCH_Result> SP_TAIKHOAN_SEARCH(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAIKHOAN_SEARCH_Result>("SP_TAIKHOAN_SEARCH", searchParameter);
        }
    
        public virtual ObjectResult<SP_TEXT_Result> SP_TEXT(Nullable<int> idmonhoc)
        {
            var idmonhocParameter = idmonhoc.HasValue ?
                new ObjectParameter("idmonhoc", idmonhoc) :
                new ObjectParameter("idmonhoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TEXT_Result>("SP_TEXT", idmonhocParameter);
        }
    
        public virtual int SP_THOIGIANDAOTAO_HANDLE(Nullable<int> ctdt, Nullable<double> tgdt)
        {
            var ctdtParameter = ctdt.HasValue ?
                new ObjectParameter("ctdt", ctdt) :
                new ObjectParameter("ctdt", typeof(int));
    
            var tgdtParameter = tgdt.HasValue ?
                new ObjectParameter("tgdt", tgdt) :
                new ObjectParameter("tgdt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THOIGIANDAOTAO_HANDLE", ctdtParameter, tgdtParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Update_HoanThanh_Sang(Nullable<int> id, Nullable<bool> finish)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_HoanThanh_Sang", idParameter, finishParameter);
        }
    
        public virtual int Update_HoanThanhCTDT_Sang(Nullable<int> id, Nullable<bool> finish)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var finishParameter = finish.HasValue ?
                new ObjectParameter("Finish", finish) :
                new ObjectParameter("Finish", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_HoanThanhCTDT_Sang", idParameter, finishParameter);
        }
    }
}
