//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucTieuDaoTao
    {
        public MucTieuDaoTao()
        {
            this.MaTran_CDRMH_CDRCTDT = new HashSet<MaTran_CDRMH_CDRCTDT>();
        }
    
        public int Id { get; set; }
        public int ChuongTrinhDaoTao_Id { get; set; }
        public string Loai { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual ChuongTrinhDaoTao ChuongTrinhDaoTao { get; set; }
        public virtual ICollection<MaTran_CDRMH_CDRCTDT> MaTran_CDRMH_CDRCTDT { get; set; }
    }
}
