//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_SEP_Team3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinChung_CTDT
    {
        public int Id { get; set; }
        public int ChuongTrinhDaoTao_Id { get; set; }
        public string TenChuongTrinh { get; set; }
        public string TenTiengAnh { get; set; }
        public string TrinhDo { get; set; }
        public string Nganh { get; set; }
        public string LoaiHinh { get; set; }
        public Nullable<double> ThoiGianDaoTao { get; set; }
        public Nullable<int> ThangDiem { get; set; }
        public string KhoiLuongKienThucToanKhoa { get; set; }
        public string DoiTuongTuyenSinh { get; set; }
        public string QuyTrinhDaoTao { get; set; }
        public string CoSoVatChat { get; set; }
        public bool Finish { get; set; }
    
        public virtual ChuongTrinhDaoTao ChuongTrinhDaoTao { get; set; }
    }
}
